### PR TITLE
Centralize python packaging logic.

### PR DESCRIPTION
**Pull request by ethanrublee**

### CODE REVIEW

**Review by edgarriba — COMMENTED** [review]
LGTM. But what about a `farm_ng_package` in the same philosophy of `farm_ng_cmake`?

**Comment by ethanrublee** [comment]
For now, i think we just make farm-ng-core the basic requirement for python.  We might end up moving farm_ng_cmake back into core not sure its worth the complexity.

**Comment by ethanrublee** [comment]
> LGTM. But what about a `farm_ng_package` in the same philosophy of `farm_ng_cmake`?

On further thought this is a decent idea, so that farm_ng_core doesn't have to bootstrap itself.

**Comment by ethanrublee** [comment]
but for later.

**Pull request merged**
